### ISSUE TITLE
Copy solr.xml to container and Copy configset 'ext_solr_12_0_0' to container fails

### ISSUE THREAD

**Issue by frankschue-sf** [ddev/ddev-typo3-solr#7]
Copying files with 
```
$ddev solrctl apply                                              
Apply config .ddev/typo3-solr/config.yaml
🐳 Copy solr.xml to container
Failed to execute command wait-for-solr.sh --wait-seconds 1: exit status 1
🐳 Copy configset 'ext_solr_12_0_0' to container
❌ 
Failed to run solrctl apply; error=exit status 1
```

After investigating the files in ddev-demo.typo3.org-typo3-solr:/var/solr/ i recognized wrong user and groups on the copied files and directories.
Adding `docker exec -i -u root ddev-"$DDEV_SITENAME"-typo3-solr chown -R solr:solr /var/solr/data/` after line 95 and `docker exec -i -u root ddev-"$DDEV_SITENAME"-typo3-solr chown -R solr:solr /var/solr/data/configsets` after line 111 in file `.ddev/commands/host/solrctl` fixed that for me.
Maybe there will be a smarter way to handle the permissions while copying files and directories...

**Comment by ochorocho** [comment]
@frankschue-sf you could try to undo your changes and run `ddev solrctl wipe` and then `ddev solrctl apply` again.

Was this a existing project where you replaced your own solr integration with the ddev/ddev-typo3-solr addon?

**Comment by frankschue-sf** [comment]
Hi Jochen,

i was playing around with https://git.typo3.org/services/demo.typo3.org/site and in initial setup that happens when post-start hook tried to execute `ddev solrctl apply`.

The files and folders where copied to the container to the right place to `/var/solr/data` but with strange owner/group combination and so the `ddev solrctl wipe` fails in cause of no permission to delete the copied files...

**Comment by frankschue-sf** [comment]
I did create an issue there as well https://git.typo3.org/services/demo.typo3.org/site/-/issues/100 before and then in investigation I came around later here.

**Comment by ochorocho** [comment]
@frankschue-sf can you do a review on this PR https://github.com/ddev/ddev-typo3-solr/pull/8
Looks like this issue only occurs on Linux (and maybe WSL).
